### ISSUE TITLE
Don't use the design support lib

### ISSUE THREAD

**Issue by blundell** [novoda/landing-strip#12]
We just use it for some animations, lets grab those and drop the deps

https://github.com/novoda/landing-strip/pull/11#issuecomment-138498176

**Comment by ouchadam** [comment]
this is the usage https://github.com/novoda/landing-strip/blob/master/core/src/main/java/android/support/design/widget/Exposer.java

**Comment by amlcurran** [comment]
What is it actually doing there? Just using adding the interpolator?

**Comment by ouchadam** [comment]
it's for `ValueAnimatorCompat`

**Comment by ataulm** [comment]
Fixed in https://github.com/novoda/landing-strip/pull/16
