### ISSUE TITLE
Add customisable tab padding support

### ISSUE THREAD

**Issue by eduardb** [novoda/landing-strip#28]
Currently, padding can be added only to the whole landing strip, and not to individual tabs. This padding (more like a margin actually) should work in such a way that the indicator is underlining only the tab text, as in the screenshot below:

<img width="367" alt="screenshot 2017-03-06 10 11 22" src="https://cloud.githubusercontent.com/assets/2426348/23603397/5438f402-0255-11e7-9474-43b5371e92bb.png">

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
