### ISSUE TITLE
State activated should be used instead of state selected

### ISSUE THREAD

**Issue by ataulm** [novoda/landing-strip#3]
I was reading this blog post the other day on [Android view states](http://ataulm.com/android-view-states/) and it was talking about how selected is more like a fallback for when focused cannot be used, and the correct state to use to designate the tab representing the current viewpager pager is `activated`.

Activated has been a state since honeycomb, and has the same affordances as selected so it's just a semantics thing.

**Comment by blundell** [comment]
blog post seems legit
