### ISSUE TITLE
Strong dependency on ViewPager is dangerous

### ISSUE THREAD

**Issue by ataulm** [novoda/landing-strip#43]
We should depend on an abstraction defined in this library, and then provide an implementation for ViewPager.

This is the same issue that the TabLayout from Material Design library faces - it depends directly on ViewPager.

ViewPager 2 is in EAP - and neither TabLayout nor Landing-Strip supports it.

Either:

1. wait for VP2 and add direct support for it
2. expose and depend on an abstraction for ViewPager (e.g. page scroll listener), so that it's easy for new implementations
3. deprecate landing-strip in favour of TabLayout, which will eventually have support for VP2 also

I think 2/3 are legit.

**Comment by tasomaniac** [comment]
What was the reason that landing-strip was not deprecated? Does it have any additional features over TabLayout?

**Comment by ataulm** [comment]
I can't remember. @ouchadam maintains it's different 😂 something along the lines of more customisability.

**Comment by ouchadam** [comment]
something something custom views, I forget 😅

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
