### ISSUE TITLE
AppCompat 22.2.0 proguard bug

### ISSUE THREAD

**Issue by ataulm** [novoda/landing-strip#6]
https://code.google.com/p/android/issues/detail?id=175086

Users of the lib will have to add this as a file for temporary workaround:

``` java
package android.support.v4.app;

public @interface DialogFragment$DialogStyle {
}
```

**Comment by ouchadam** [comment]
:100:

**Comment by blundell** [comment]
why is everything in teh `android.support.v4.app` package not supported. Are you inheriting from the base proguard file? _goes and looks_

**Comment by blundell** [comment]
.. I don't see you using proguard in the demo. Are you sure this is an issue if they have a correct proguard setup? i.e. reproduce in the demo module or close as not our concern :)

**Comment by ataulm** [comment]
I'll add a demo today if time :tongue:

**Comment by ataulm** [comment]
Turns out I'm a liar liar pants on fire.

This is happening when your project includes some annotation processing - a detailed investigation by this industrious fellow: https://github.com/excilys/androidannotations/issues/1435

**Comment by ouchadam** [comment]
![](http://i.imgur.com/kD0Oar5.gif)
